myshop/cart/urls.py
from django.conf.urls import url
from .views import *

app_name = 'cart'
urlpatterns = [
         url(r'^$',cart_detail,name='cart_detail'),
         url(r'^add/(?P<product_id>\d+)/$',cart_add,name='cart_add'),
         url(r'^remove/(?P<product_id>\d+)/$',cart_remove,name='cart_remove')
    ]

myshop/login/urls.py
from django.conf.urls import include,url
from login.views import *
from django.contrib.auth import views as auth_views

app_name="login"
urlpatterns = [
     url(r'^$',login,name='login'),
    url(r'^auth_view/$',auth_view,name="auth_view"),
    url(r'^logout/$',logout,name="logout"),
    url(r'^loggedin/$',loggedin),
    url(r'^invalid/$',invalid_login),
    url(r'^register/$',register_user,name='register'),
    url(r'^register_success/$',register_success,name="success")
   
    ]                  

myshop/myshop/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

#app_name = "myshop"
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cart/',include('cart.urls',namespace='cart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^mylog/', include('login.urls', namespace='mylogin')),
    url(r'^payment/', include('payment.urls', namespace='payment')),
    url(r'^paypal/',include('paypal.standard.ipn.urls')),
    url(r'',include('shop.urls',namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

myshop/shop/urls.py
from django.conf.urls import url
from .views import *

app_name='shop'
urlpatterns = [
    url(r'^$',product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$',product_list,name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',product_detail,name='product_detail'),
    #url(r'^$',pro_det),
]
    

myshop/login/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

myshop/login/forms.py
import re
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

class RegistrationForm(forms.Form):

    username = forms.CharField(widget=forms.TextInput(attrs=dict(required=True,max_length=30)))
    email = forms.EmailField(widget=forms.TextInput(attrs=dict(required=True,max_length=30)))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs=dict(required=True, max_length=30,render_value=False)))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs=dict(required=True,max_length=30,render_value=False)))

    def clean_username(self):
        try:
            user = User.objects.get(username__iexact=self.cleaned_data['username'])
        except User.DoesNotExist:
            return self.cleaned_data['username']
        raise forms.ValidationError(_("The username already exists. plz try another one."))
    
    def clean(self):
        if 'password1' in self.cleaned_data and 'password2' in self.cleaned_data:
            if self.cleaned_data['password1'] != self.cleaned_data['password2']:
                raise forms.ValidationError(_("the two password fields did not match."))
            return self.cleaned_data

myshop/login/views.py
from django.shortcuts import render,redirect
from django.http import *
from django.contrib import auth
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
#from django.core.context_processors import csrf
from django.contrib.auth.forms import UserCreationForm
from .forms import *

def login(request):
    return render(request,'login.html')

def auth_view(request):
    
    username = request.POST['username']
    password = request.POST['password']
    m=User.objects.get(username=username)
    user = auth.authenticate(username=username,password=password)
    

    if user is not None:
        auth.login(request,user)
        #request.session['user_id']=m.id
        return redirect('orders:order_create',username)
    else:
        return HttpResponseRedirect('/invalid/')
        #return HttpResponse('Username Or password did not match..!')
        #form = RegistrationForm()
        #return render_to_response('login.html',{'form':form})
    """

    m=User.objects.get(username=username)
    if m.password == request.POST['password']:
        print "hello"
        request.session['user_id']=m.id
        return HttpResponse("You are logged in")
    else:
        return HttpResponse("Incorrect password")
    """   
def loggedin(request):
    if request.user.is_authenticated():
        return render(request,'loggedin.html',{'fullname':request.user.username})
    else:
        return HttpResponse('Page not found')

    
def invalid_login(request):
    return render(request,'invalid_login.html')

def logout(request):
    #print 'session:',request.session
    #del request.session['user_id']
    auth.logout(request)
    return HttpResponseRedirect('/')
        
    
def register_user(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            #form.save() or define save() in forms.py then call it...
            user = User.objects.create_user(
            username = form.cleaned_data['username'],
            password = form.cleaned_data['password1'],
            email = form.cleaned_data['email'])
            
            return redirect('mylogin:success')

    else:
        form = RegistrationForm()
    return render(request,'register.html',{'form':form})    


def register_success(request):
    
    return render(request,'register_success.html')
    

myshop/login/templates/invalid_login.html
{% block content %}
       
		<h2> Login details are invalid..!</h2>
		<p>click <a href="/">here</a> to login again.</p>
     
{% endblock %}	 

myshop/login/templates/loggedin.html
{% block content %}
       
		<h2> hi...{{ fullname }}..! You are Logged in</h2>
		<p>click <a href="/logout/">here</a> to logout.</p>
     
{% endblock %}	 

myshop/login/templates/login.html
{% extends "base1.html" %}
{% load static %}

	
        
 
<!--
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>{% block title %}My shop{% endblock %}</title>
	<link rel="stylesheet" href="/static/css/bootstrap.min.css">
	
        
    <link href="{% static "css/base.css" %}" rel="stylesheet">
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
     <div class="navbar-header" style="padding-left:20px;padding-top:15px">
      <p style="font-size:20px;color:white"><b>My shop</b>
	  <a href="{% url "shop:product_list" %}" style="padding-left:40px"><span class="glyphicon glyphicon-home"></span></a>
	  </p>
	  
    </div>
   
    <ul class="nav navbar-nav navbar-right">
	
	
      <li><a style="color:white" href="{% url "mylogin:register" %}">Register</a></li>
      <li><a style="color:white" href="{% url "mylogin:login" %}">Login</a></li>
	   <li><a style="color:white" href="#">Contact Us</a></li>
    </ul>
  </div>
</nav>
-->
{% block content %}
 {% if form.error %}
  <p>password not correct</p>
 
 {% endif %}
 
       
	   <h3><b>Login</b></h3><br />
	   <form role="form" action="{% url "mylogin:auth_view" %}" method="post" class="login-form">{% csrf_token %}
			                    	<div class="form-group">
			                    		<label>Username</label>
			                        	<input type="text" name="username" placeholder="Username" class="form-control">
			                        </div><br />
			                        <div class="form-group">
			                        	<label>Password</label>
			                        	<input type="password" name="password" placeholder="Password" class="form-control">
			                        </div>
			                        <button type="submit" class="btn btn-primary btn-md">Sign in!</button>
	  </form>
	   <!--
		<h2 style="width:300px;height:40px;background-color:gray;font-family:stencil;font-size:25px;padding-top:15px"><center>Login</center></h2>
		<form method="post" action="{% url "mylogin:auth_view" %}">{% csrf_token %}
		    <table border="0">
			   <tr height=50px><th><label for="id_username">Username:</label></th><td><input type="text" name="username" value="" id="username"></td></tr>
			   <tr height=50px><th><label for="id_password">Password:</label></th><td><input type="password" name="password" value="" id="password"></td></tr>
			</table><br>
            <input type="submit" value="Login" />
            
	    </form>
		
  -->

    
	
{% endblock %}	 

myshop/login/templates/register.html
{% block content %}
       
		
		<div style="width:300px;height:200px;margin-left:350px;">
		<h2 style="width:300px;height:40px;background-color:gray;font-family:stencil;font-size:25px;padding-top:15px"><center>Register</center></h2>
		<form action='{% url "mylogin:register" %}' method='post'> {% csrf_token %}
		
		<table border=0>
		<tr height=50px><td>Username: </td> <td> <input type="text" name="username" /></td></tr>
		
		<tr height=50px><td>Email-ID:</td>   <td><input type="email" name="email" /></td></tr>
		<tr height=50px><td>Password:</td>  <td><input type="password" name="password1" /></td></tr>
		<tr height=50px><td>Confirm Password:</td>  <td><input type="password" name="password2" /></td></tr>
		
		</table><br><br>
		<input type='submit' value='Register' />
		
		</form>
		
		</div>
     
{% endblock %}	 

myshop/login/templates/register_success.html
{% extends "shop/header.html" %}
{% block content %}
       
		<h2>Thanks..! You have Registered</h2>
		
     
{% endblock %}	 