myshop/cart/urls.py
from django.conf.urls import url
from .views import *

app_name = 'cart'
urlpatterns = [
         url(r'^$',cart_detail,name='cart_detail'),
         url(r'^add/(?P<product_id>\d+)/$',cart_add,name='cart_add'),
         url(r'^remove/(?P<product_id>\d+)/$',cart_remove,name='cart_remove')
    ]

myshop/login/urls.py
from django.conf.urls import include,url
from login.views import *
from django.contrib.auth import views as auth_views

app_name="login"
urlpatterns = [
     url(r'^$',login,name='login'),
    url(r'^auth_view/$',auth_view,name="auth_view"),
    url(r'^logout/$',logout,name="logout"),
    url(r'^loggedin/$',loggedin),
    url(r'^invalid/$',invalid_login),
    url(r'^register/$',register_user,name='register'),
    url(r'^register_success/$',register_success,name="success")
   
    ]                  

myshop/myshop/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

#app_name = "myshop"
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cart/',include('cart.urls',namespace='cart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^mylog/', include('login.urls', namespace='mylogin')),
    url(r'^payment/', include('payment.urls', namespace='payment')),
    url(r'^paypal/',include('paypal.standard.ipn.urls')),
    url(r'',include('shop.urls',namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

myshop/shop/urls.py
from django.conf.urls import url
from .views import *

app_name='shop'
urlpatterns = [
    url(r'^$',product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$',product_list,name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',product_detail,name='product_detail'),
    #url(r'^$',pro_det),
]
    

myshop/cart/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

myshop/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i,str(i)) for i in range(1,21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,
                                      coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

myshop/cart/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import *
from django.http import *
from django.urls import reverse

# Create your views here.

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,quantity=cd['quantity'],
                 update_quantity=cd['update'])
    
    
    return redirect('cart:cart_detail')
    #return render(request,'detail.html',{'cart':cart})

def cart_remove(request,product_id):
    cart = Cart(request)
    product = get_object_or_404(Product,id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],'update': True})
    
    return render(request,'cart/detail.html',{'cart':cart})

myshop/cart/templates/cart/detail.html
{% extends "base1.html" %}
{% load static %}

{% block title %}
    Your shopping cart
{% endblock %}

{% block content %}
    <h1>Shopping cart</h1>
    <table class="cart">
        <thead>
            <tr>
                <th>Image</th>
                <th>Product</th>
                <th>Quantity</th>
                <th>Remove</th>
                <th>Unit price</th>                
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
            <tr>
                <td>
                    <a href="{{ product.get_absolute_url }}">
                        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
                    </a>
                </td>
                <td>{{ product.name }}</td>
                <td>
                    <form action="{% url "cart:cart_add" product.id %}" method="post">
                        {{ item.update_quantity_form.quantity }}
                        {{ item.update_quantity_form.update }}
                        <input type="submit" value="Update">
                        {% csrf_token %}
                    </form>
                </td>
				
                <td><a href="{% url "cart:cart_remove" product.id %}"><span class="glyphicon glyphicon-trash"></span></a></td>
                
				<td class="num">${{ item.price }}</td>
                <td class="num">${{ item.total_price }}</td>
            </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Total</td>
            <td colspan="4"></td>
            <td class="num">${{ cart.get_total_price }}</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
	                 
        <a href="{% url "shop:product_list" %}" class="btn btn-primary btn-md">Continue shopping</a>
      
		<a href="{% url "mylogin:login" %}" class="btn btn-primary btn-md">Proceed to Checkout</a>
    </p>
{% endblock %}